--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Debian 16.2-1.pgdg120+2)
-- Dumped by pg_dump version 16.2

-- Started on 2024-04-21 16:52:29

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

-- CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 3395 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16385)
-- Name: Account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Account" (
    "Id" uuid NOT NULL,
    "Number" character varying(50) NOT NULL,
    "CustomerId" uuid,
    "IsDeleted" boolean NOT NULL
);


ALTER TABLE public."Account" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16388)
-- Name: Customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Customer" (
    "Id" uuid NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Name" text NOT NULL
);


ALTER TABLE public."Customer" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16393)
-- Name: Transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Transaction" (
    "Id" uuid NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "StatusId" integer NOT NULL,
    "RecipientAccountId" uuid,
    "SenderAccountId" uuid NOT NULL,
    "Amount" numeric NOT NULL,
    "AccountId" uuid
);


ALTER TABLE public."Transaction" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16398)
-- Name: TransactionStatuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TransactionStatuses" (
    "Id" integer NOT NULL,
    "Description" text NOT NULL,
    "Name" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."TransactionStatuses" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16404)
-- Name: TransactionStatuses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TransactionStatuses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TransactionStatuses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16405)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3384 (class 0 OID 16385)
-- Dependencies: 215
-- Data for Name: Account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Account" ("Id", "Number", "CustomerId", "IsDeleted") FROM stdin;
\.


--
-- TOC entry 3385 (class 0 OID 16388)
-- Dependencies: 216
-- Data for Name: Customer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Customer" ("Id", "IsDeleted", "Name") FROM stdin;
\.


--
-- TOC entry 3386 (class 0 OID 16393)
-- Dependencies: 217
-- Data for Name: Transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Transaction" ("Id", "IsDeleted", "StatusId", "RecipientAccountId", "SenderAccountId", "Amount", "AccountId") FROM stdin;
\.


--
-- TOC entry 3387 (class 0 OID 16398)
-- Dependencies: 218
-- Data for Name: TransactionStatuses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TransactionStatuses" ("Id", "Description", "Name") FROM stdin;
1	Транзакция создана	Created
2	Транзакция в обработке	Processing
3	Транзакция обработана	Completed
4	Транзакция отменена	Cancelled
\.


--
-- TOC entry 3389 (class 0 OID 16405)
-- Dependencies: 220
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240421132132_Initial	8.0.2
20240421132928_nametrstatus	8.0.2
\.


--
-- TOC entry 3396 (class 0 OID 0)
-- Dependencies: 219
-- Name: TransactionStatuses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TransactionStatuses_Id_seq"', 1, false);


--
-- TOC entry 3223 (class 2606 OID 16409)
-- Name: Account PK_Account; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "PK_Account" PRIMARY KEY ("Id");


--
-- TOC entry 3225 (class 2606 OID 16411)
-- Name: Customer PK_Customer; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Customer"
    ADD CONSTRAINT "PK_Customer" PRIMARY KEY ("Id");


--
-- TOC entry 3231 (class 2606 OID 16413)
-- Name: Transaction PK_Transaction; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "PK_Transaction" PRIMARY KEY ("Id");


--
-- TOC entry 3233 (class 2606 OID 16415)
-- Name: TransactionStatuses PK_TransactionStatuses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TransactionStatuses"
    ADD CONSTRAINT "PK_TransactionStatuses" PRIMARY KEY ("Id");


--
-- TOC entry 3235 (class 2606 OID 16417)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3220 (class 1259 OID 16418)
-- Name: IX_Account_CustomerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Account_CustomerId" ON public."Account" USING btree ("CustomerId");


--
-- TOC entry 3221 (class 1259 OID 16419)
-- Name: IX_Account_Number; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Account_Number" ON public."Account" USING btree ("Number");


--
-- TOC entry 3226 (class 1259 OID 16420)
-- Name: IX_Transaction_AccountId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transaction_AccountId" ON public."Transaction" USING btree ("AccountId");


--
-- TOC entry 3227 (class 1259 OID 16421)
-- Name: IX_Transaction_RecipientAccountId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transaction_RecipientAccountId" ON public."Transaction" USING btree ("RecipientAccountId");


--
-- TOC entry 3228 (class 1259 OID 16422)
-- Name: IX_Transaction_SenderAccountId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transaction_SenderAccountId" ON public."Transaction" USING btree ("SenderAccountId");


--
-- TOC entry 3229 (class 1259 OID 16423)
-- Name: IX_Transaction_StatusId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Transaction_StatusId" ON public."Transaction" USING btree ("StatusId");


--
-- TOC entry 3236 (class 2606 OID 16424)
-- Name: Account FK_Account_Customer_CustomerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "FK_Account_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES public."Customer"("Id") ON DELETE SET NULL;


--
-- TOC entry 3237 (class 2606 OID 16429)
-- Name: Transaction FK_Transaction_Account_AccountId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_Account_AccountId" FOREIGN KEY ("AccountId") REFERENCES public."Account"("Id");


--
-- TOC entry 3238 (class 2606 OID 16434)
-- Name: Transaction FK_Transaction_Account_RecipientAccountId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_Account_RecipientAccountId" FOREIGN KEY ("RecipientAccountId") REFERENCES public."Account"("Id") ON DELETE SET NULL;


--
-- TOC entry 3239 (class 2606 OID 16439)
-- Name: Transaction FK_Transaction_Account_SenderAccountId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_Account_SenderAccountId" FOREIGN KEY ("SenderAccountId") REFERENCES public."Account"("Id") ON DELETE SET NULL;


--
-- TOC entry 3240 (class 2606 OID 16444)
-- Name: Transaction FK_Transaction_TransactionStatuses_StatusId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Transaction"
    ADD CONSTRAINT "FK_Transaction_TransactionStatuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES public."TransactionStatuses"("Id") ON DELETE CASCADE;


-- Completed on 2024-04-21 16:52:29

--
-- PostgreSQL database dump complete
--

